# Generated by Django 5.2 on 2025-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_order_billing_address_remove_order_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, help_text='Шлях до зображення у статичних файлах', max_length=255, null=True),
        ),
    ]
