# Generated by Django 5.2 on 2025-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nova_poshta_city_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
